### ISSUE TITLE
IV:MP Core Failed to Initialize

### ISSUE THREAD

**Issue by BlueCatIV** [IV-Multiplayer/bugs#1]
![Screenshot (183)](https://user-images.githubusercontent.com/85974813/130700862-a66dfea9-413a-43ad-a6a0-80e53d707cb4.png)

**Comment by alextwothousand** [comment]
Which game version did you use?

**Comment by BlueCatIV** [comment]
1.1.2.0

**Comment by alextwothousand** [comment]
Thanks a bunch, I will add more useful debugging messages, hopefully allowing us to mitigate this issue!
